### ISSUE TITLE
Bug when trying to load music - Could not load the title for…

### ISSUE THREAD

**Issue by shemetz** [ghost-fvtt/audio-metadata-reader#28] opened 2022-10-11 17:21 UTC
### Expected Behavior

When trying to load the “CelestialMemories” MP3 file from the Tabletop RPG Music module, I got a warning message (“Could not load the title for…”) and it was set as “Celestialmemories”.
1. This is probably a bug
2. Why change it to “Celestialmemories” and not “CelestialMemories”?  Maintaining capitalization should be easy and more useful for the average user.

### Current Behavior

Error in console, though the track was still loaded as normal.

### Steps to Reproduce

1. install Tabletop RPG Music module and enable it
2. open one of the music playlist compendiums from that module
3. attempt to load one of the tracks

### Version

v1.0.1

### Foundry VTT Version

v10.285

### Operating System

Windows

### Browser / App

Chrome

### Game System

pf2e

**Comment by ghost91-** [comment] 2022-10-12 11:57
Thanks for the report, I'll take a look as soon as possible to figure out why it can't load that particular file.

Regarding capitalization: The logic used to set the name when the file cannot be loaded is the same that's used by foundry core. The idea is that we use the default behavior as fallback, if reading the metadata is not possible, for whatever reason. So I don't think I will change that. Could you check if the capitalization is the same in foundry core (i.e., with the module disabled)? If it is different, then it's a bug, but otherwise, it's the desired behavior.

**Comment by shemetz** [comment] 2022-10-12 12:01
Sorry, I can't check anymore as I've uninstalled both modules, but I think it's alright that the default is the core behavior.

**Comment by ghost91-** [comment] 2022-10-17 20:52
It turns out, there is a simple reason for this behavior: The audio files provided by the Tabletop RPG Music module don't include title tags. So Audio Metadata Reader behaves exactly as expected. It's still no ideal, of course, so I created an issue for the Tabletop RPG Music module to add title tags for their audio files: https://github.com/Tabletop-RPG-Music/tabletop-rpg-music/issues/6.

Closing this, as the issue is not related to Audio Metadata Reader.

**Closed by ghost91-** 2022-10-17 20:52 UTC
Labels: bug
